platform :ios, '11.0'

use_frameworks! 

target 'Example-iOS_ObjC' do
  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth', :path => '../../'
end

target 'Example-iOS_ObjC_Extension' do    
    # AppAuth/Core Pod
    # In production, just use `pod 'AppAuth/Core'` without the path reference.
    pod 'AppAuth/Core', :path => '../../'
end
