platform :ios, '9.0'

target 'Example-iOS_ObjC' do
  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth', :path => '../../'
end

target 'Example-iOS_ObjC_Extension' do    
    # AppAuth Pod
    # In production, just use `pod 'AppAuth'` without the path reference.
    pod 'AppAuth', :path => '../../'
end
