name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  xcode-project-test:
    runs-on: macos-12
    strategy:
      matrix:
        flags: [
          "-scheme AppAuth-iOS -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.2' -sdk 'iphonesimulator16.2'",
          "-scheme AppAuth-macOS -destination 'platform=macOS,arch=x86_64' -sdk 'macosx13.1'",
          "-scheme AppAuth_macOS -destination 'platform=macOS,arch=x86_64' -sdk 'macosx13.1'",
          "-scheme AppAuth-tvOS -destination 'platform=tvOS Simulator,name=Apple TV,OS=16.1' -sdk 'appletvsimulator16.1'",
          "-scheme AppAuth_tvOS -destination 'platform=tvOS Simulator,name=Apple TV,OS=16.1' -sdk 'appletvsimulator16.1'",
          "-scheme AppAuthTV -destination 'platform=tvOS Simulator,name=Apple TV,OS=16.1' -sdk 'appletvsimulator16.1'"
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Run unit test targets
      run: |
        xcodebuild test \
          -project AppAuth.xcodeproj \
          ${{ matrix.flags }}

  pod-lib-lint:
    runs-on: macos-12
    strategy:
      matrix:
        flags: [
          '',
          '--use-libraries',
          '--use-static-frameworks'
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install Ruby gems with Bundler
      run: bundle install
    - name: Lint podspec using local source
      run: pod lib lint --verbose ${{ matrix.flags }}

  spm-build-test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build unit test target
      run: swift build
    - name: Run unit test target
      run: swift test --enable-code-coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
